stages:
  - app
  - db
  - build
  - deploy

app:
  stage: app
  image: python:3.13-slim
  script:
    - pip --version
    - python --version
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - python manage.py test
    - python -c "import fastapi; import uvicorn; import psycopg; import redis; import rq; import celery; import sqlalchemy; print('All dependencies are installed and importable')"

db:
  stage: db
  image: python:3.13-slim
  services:
    - name: postgres:16-alpine
      alias: db

  variables:
    POSTGRES_USER: "mansur_admin"
    POSTGRES_PASSWORD: "123"
    POSTGRES_DB: "uptime_monitor"
    POSTGRES_HOST: "db"
    POSTGRES_PORT: "5432"
  script:
    - pip --version
    - pip install -r requirements.txt
    - python -c "import psycopg; conn = psycopg.connect(host='$POSTGRES_HOST', port='$POSTGRES_PORT', dbname='$POSTGRES_DB', user='$POSTGRES_USER', password='$POSTGRES_PASSWORD'); print('PostgreSQL connection successful'); conn.close()"

build:
  stage: build
  image: docker:27-cli
  services:
    - docker:27-dind
  variables:
    IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"
  script:
    - docker --version
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$IMAGE_TAG"
  
deploy:
  stage: deploy
  image: docker:27-cli
  services:
    - docker:27-dind
  variables:
    IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"
  script:
    - docker --version
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker pull "$CI_REGISTRY_IMAGE:$IMAGE_TAG" 
    - echo "This stage is not working yet, but the image was pulled successfully"



    
